### ISSUE TITLE
Add Maven compiler configuration <release>11</release>

### ISSUE THREAD

**Issue by axkr** [danielNaczo/Python3Parser#6]
I get the following error using your library:
```
java.lang.UnsupportedClassVersionError: io/github/danielnaczo/python3parser/visitors/basic/Python3ASTVisitor has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0 
```

Can you compile for Java 11 usage by inserting this tag
```xml
<target>11</target>
```

here:
https://github.com/danielNaczo/Python3Parser/blob/0668732835b162d92b872933b94d7aa69ce4ce64/pom.xml#L81

and republish for Maven please.

**Comment by danielNaczo** [comment]
Hey Axel,

try to use version 1.0.4 into the version-tag of the dependency: https://central.sonatype.com/artifact/io.github.danielnaczo/python3parser/1.0.4
This version has been built with Java 11.

This should fix your problem.

Kind regards,
Daniel

**Comment by axkr** [comment]
It seems, that I'm now having problems with the antlr version. I'm using `antlr4-runtime` version `4.13.1` for the other modules in the project. 

```java
java.lang.NoClassDefFoundError: Could not initialize class io.github.danielnaczo.python3parser.Python3Lexer
	at io.github.danielnaczo.python3parser.utilities.ASTParser.parseExpressionModWithCode(ASTParser.java:33)
	at org.matheclipse.core.sympy2symja.SympyToSymjaExpr.toSymjaForm(SympyToSymjaExpr.java:87)
	at org.matheclipse.core.sympy2symja.SympyToSymjaTest.check(SympyToSymjaTest.java:30)
	at org.matheclipse.core.sympy2symja.SympyToSymjaTest.testBessel(SympyToSymjaTest.java:19)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsupportedOperationException: java.io.InvalidClassException: org.antlr.v4.runtime.atn.ATN; Could not deserialize ATN with version 3 (expected 4). [in thread "main"]
	at org.antlr.v4.runtime.atn.ATNDeserializer.deserialize(ATNDeserializer.java:56)
	at org.antlr.v4.runtime.atn.ATNDeserializer.deserialize(ATNDeserializer.java:48)
	at io.github.danielnaczo.python3parser.Python3Lexer.<clinit>(Python3Lexer.java:751)
	at io.github.danielnaczo.python3parser.utilities.ASTParser.parseExpressionModWithCode(ASTParser.java:33)
	at org.matheclipse.core.sympy2symja.SympyToSymjaExpr.toSymjaForm(SympyToSymjaExpr.java:87)
	at org.matheclipse.core.sympy2symja.SympyToSymjaTest.check(SympyToSymjaTest.java:30)
	at org.matheclipse.core.sympy2symja.SympyToSymjaTest.testPower(SympyToSymjaTest.java:25)
	... 1 more
```
